version: '3.3'

services:
  redis:
      image: redis

  # Dashboard app
  dashboard:
      # Dashboard image is also pulled from DockerHub
      image: albbasdur/seal-dashboard-packaging:latest
      command: uwsgi-sa
      ports:
        - 443:443
      dns:
        - 127.0.0.11
      depends_on:
        - redis
      environment:
        # Need because the code can work standalone
        - USING_DOCKER=True
        # Set to false when run in production
        - DEBUG=True
        # Set for the dashboard endpoint SEAL URL access
        - SEAL_ENDPOINT=<DASHBOARD_ENDPOINT_URL>
        # Set to true if a proxy is configured
        - USE_PROXY=False
        # Proxy endpoints in case it is set up  
        - SEAL_PROXY_HTTP_ENDPOINT=<SEAL_PROXY_HTTP_URL>
        - SEAL_PROXY_HTTPS_ENDPOINT=<SEAL_PROXY_HTTPS_URL>
        # Endpoint for SEAL microservices
        - SEAL_SERVICE_URL=<SEAL_SERVICE_ENDPOINT_URL>
        # Certificate key path mounted in certs directory
        - KEY_PATH=certs/<CERTIFICATE_KEY>.key
        # Certificate path mounted in certs directory
        - CERT_PATH=certs/<CERTIFICATE>.crt
        # Dashboard uWSGI port
        - DASHBOARD_PORT=443
        # We use redis as distributes key-value store
        # Set to the machine where redis is running
        - REDIS=redis
      volumes:
        - ./<PATH_TO_CERTIFICATE_AND_KEY_DIRECTORY>:/var/www/seal/certs
